blog/urls.py
from django.conf.urls import url

from .views import (BlogView, TagView, ArchiveView, SearchView,
                    ArticleView)


urlpatterns = [
    # Examples:
    # url(r'^$', 'jonah.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', BlogView.as_view(), name='index'),
    url(r'^search$', SearchView.as_view(), name='search'),
    url(r'^tag/(?P<tag_id>[0-9]{1,2})/$', TagView.as_view(), name='tag'),
    url(r'^archive/(?P<year>20[0-9]{2})/$', ArchiveView.as_view(),
        name='archive'),
    url(r'^article/(?P<slug>[0-9a-zA-Z_-]+)$', ArticleView.as_view(),
        name='article'),
]

project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.views.generic import TemplateView

from blog import views as blog_views, urls as blog_urls
from comment import urls as comment_urls
from message import urls as message_urls

urlpatterns = [
    # Examples:
    # url(r'^$', 'project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', blog_views.HomeView.as_view(), name='home'),
    url(r'^blog/', include(blog_urls, namespace='blog', app_name='blog')),
    url(r'^comment/', include(comment_urls, namespace='comment',
                              app_name='comment')),
    url(r'^message/', include(message_urls, namespace='message',
                              app_name='message')),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'),
        name='about')
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),
    ]

blog/models.py
from django.db import models

# Create your models here.


class Column(models.Model):
    "专栏模型"
    name = models.CharField(max_length=16, verbose_name="名字")

    class Meta:
        verbose_name_plural = verbose_name = "专栏"
        ordering = ['name']

    def __str__(self):
        return self.name


class Tag(models.Model):
    "标签模型"
    name = models.CharField(max_length=16, verbose_name="名字")

    class Meta:
        verbose_name_plural = verbose_name = "标签"
        ordering = ['name']

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse("blog:tag", kwargs={'tag_id': self.pk})

    def __str__(self):
        return self.name


class Article(models.Model):
    "文章模型"
    title = models.CharField(max_length=128, verbose_name="标题")
    slug = models.SlugField(verbose_name="路径")
    column = models.ForeignKey("Column", verbose_name="专栏")
    tag = models.ForeignKey("Tag", verbose_name="标签")
    summary = models.TextField(verbose_name="摘要")
    content = models.TextField(verbose_name="正文")
    recommend = models.BooleanField(default=False)
    recommend_pic = models.ImageField(
        upload_to="recommend", default="recommend/default.jpg"
    )
    created_time = models.DateField(auto_now_add=True, verbose_name="创建时间")
    visited_times = models.IntegerField(default=0, verbose_name="访问次数")

    class Meta:
        verbose_name_plural = verbose_name = "文章"
        ordering = ['-created_time']

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse("blog:article", kwargs={'slug': self.slug})

    def __str__(self):
        return self.title

comment/models.py
from django.db import models

from blog.models import Article

# Create your models here.


class Comment(models.Model):
    "评论模型"
    nickname = models.CharField(max_length=32, verbose_name='昵称')
    email = models.EmailField(verbose_name='邮箱')
    content = models.TextField(max_length=1000, verbose_name='内容')
    up_times = models.IntegerField(default=0, verbose_name='赞同')
    related_article = models.ForeignKey(Article, verbose_name='文章')
    created_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = verbose_name = "评论"
        ordering = ['created_time']

    def __str__(self):
        return self.nickname + '的评论'


class SubComment(models.Model):
    "评论回复模型"
    nickname = models.CharField(max_length=32, verbose_name='昵称')
    email = models.EmailField(verbose_name='邮箱')
    content = models.TextField(max_length=1000, verbose_name='内容')
    related_comment = models.ForeignKey(Comment, verbose_name='评论')
    created_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = verbose_name = "评论回复"
        ordering = ['created_time']

    def __str__(self):
        return self.nickname + '的评论回复'

blog/views.py
import re

from django.shortcuts import get_object_or_404, Http404, HttpResponse
from django.core.cache import caches
from django.views.generic.list import ListView
from django.conf import settings
from django.db.models import Q
from django.utils import timezone

from comment.models import Comment
from .models import Article, Column, Tag

# Create your views here.
# 缓存
try:
    CACHE = caches['memcache']
except ImportError:
    CACHE = caches['default']


class ArticleMixin(object):
    articles = Article.objects.all()


class ColumnMixin(object):
    columns = Column.objects.all()


class TagMixin(object):
    tags = Tag.objects.all()


class HomeView(ArticleMixin, ListView):
    "首页视图"
    template_name = 'home.html'

    def get_queryset(self):
        return self.articles

    def get_context_data(self, **kwargs):
        kwargs['recents'] = self.articles[:7]  # 最近文章
        kwargs['hots'] = self.articles.order_by('-visited_times')[:7]  # 热门文章
        kwargs['recommends'] = self.articles.filter(recommend=True)  # 推荐文章
        kwargs['notice'] = settings.NOTICE  # 通知框内容
        return super(HomeView, self).get_context_data(**kwargs)


class BlogView(ArticleMixin, ColumnMixin, TagMixin, ListView):
    "博客页视图"
    context_object_name = 'articles'
    paginate_by = settings.PAGE_NUM  # 分页

    def get_template_names(self):
        if self.request.is_ajax():
            return 'widgets/article-list.html'  # ajax请求时使用的模板
        return 'blog.html'

    def get_queryset(self):
        column_id = self.request.GET.get('column_id', '')

        # 如果请求包含关键字参数column_id,返回对应专栏的文章,否则返回所有文章作为queryset
        if column_id:
            self.column = get_object_or_404(self.columns, id=column_id)
            articles = self.articles.filter(column=self.column.id)
        else:
            self.column = None
            articles = self.articles

        return articles

    def get_archives(self):
        "按年份归档并返回每年的文章数目"
        archives = dict()
        current_year = timezone.datetime.today().year

        for year in range(2017, current_year + 1):
            num = len(self.articles.filter(created_time__year=year))
            archives[year] = num

        return archives

    def get_context_data(self, **kwargs):
        kwargs['tags'] = self.tags  # 标签
        kwargs['tags_num'] = len(self.tags)  # 标签数目
        kwargs['columns'] = self.columns  # 所有专栏
        kwargs['this_column'] = self.column  # 请求的专栏
        kwargs['archives'] = self.get_archives()  # 归档
        return super(BlogView, self).get_context_data(**kwargs)


class ArticleView(ArticleMixin, ListView):
    "详细呈现一篇文章, 分页获取文章评论"
    context_object_name = 'comments'
    paginate_by = settings.PAGE_NUM

    def get_template_names(self):
        if self.request.is_ajax():
            return 'widgets/comment-list.html'
        return 'article-detail.html'

    def get_queryset(self):
        return Comment.objects.filter(related_article=self.article)  # 获取评论

    def get_context_data(self, **kwargs):
        page = self.request.GET.get('page', '')
        try:
            # 前面的评论数目
            # 如获取第 3 页评论(page=3),每页先是10条评论,则 prev_mun = (3-1)*10 = 20
            # 从而可知, 第 3 页获取的是第 21 条到第 30 条评论(共10条)
            prev_num = (int(page) - 1) * settings.PAGE_NUM
        except ValueError:
            # 请求没有提交page参数时, 返回第 1 页评论, prev_num = 0
            prev_num = 0
        kwargs['prev_num'] = prev_num
        kwargs['article'] = self.article
        return super(ArticleView, self).get_context_data(**kwargs)

    def get(self, request, *args, **kwargs):
        slug = self.kwargs.get('slug')
        self.article = get_object_or_404(self.articles, slug=slug)

        # 统计文章被访问次数
        if 'HTTP_X_FORWARDED_FOR' in self.request.META:
            current_ip = self.request.META['HTTP_X_FORWARDED_FOR']
        else:
            current_ip = self.request.META['REMOTE_ADDR']

        # 获取15*60s时间内访问过这篇文章的所有ip
        visited_ips = CACHE.get(slug, [])

        # 如果ip不存在则浏览次数+1
        if current_ip not in visited_ips:
            self.article.visited_times += 1
            self.article.save()
            visited_ips.append(current_ip)

            # 更新缓存
            CACHE.set(slug, visited_ips, 15 * 60)

        return super(ArticleView, self).get(request, *args, **kwargs)


class SearchView(ArticleMixin, ListView):
    "按搜索的关键词,返回文章的搜索结果"
    context_object_name = 'articles'
    paginate_by = settings.PAGE_NUM

    def get_template_names(self):
        if self.request.is_ajax():
            return 'widgets/article-list.html'
        return 'search-result.html'

    def get_queryset(self):
        # 在文章题目,概要和内容中查找并返回含有该关键词的文章
        articles = self.articles.filter(
            Q(title__icontains=self.key) | Q(summary__icontains=self.key) |
            Q(content__icontains=self.key)
        )
        self.count = len(articles)
        return articles

    def get_context_data(self, **kwargs):
        kwargs['key'] = self.key
        kwargs['count'] = self.count
        return super(SearchView, self).get_context_data(**kwargs)

    def get(self, request, *args, **kwargs):
        key = self.request.GET.get('key', '').strip()  # 搜索关键词
        if key:
            reg = re.compile(r'[\w\'-]')
            self.key = ''.join([k for k in list(key) if reg.match(k)])
        else:
            self.key = ''
        if not self.key:
            return HttpResponse("<h3>请输入有效搜索关键词</h3>")
        return super(SearchView, self).get(request, *args, **kwargs)


class TagView(ArticleMixin, TagMixin, ListView):
    "标签视图, 返回该标签的对应文章的列表"
    context_object_name = 'articles'
    paginate_by = settings.PAGE_NUM

    def get_template_names(self):
        if self.request.is_ajax():
            return 'widgets/article-list.html'
        return 'tag.html'

    def get_queryset(self):
        tag_id = self.kwargs.get('tag_id')
        self.tag = get_object_or_404(self.tags, id=tag_id)
        articles = self.articles.filter(tag=self.tag.id)  # 获取该标签的文章
        self.count = len(articles)
        return articles

    def get_context_data(self, **kwargs):
        kwargs['tag'] = self.tag
        kwargs['count'] = self.count
        return super(TagView, self).get_context_data(**kwargs)


class ArchiveView(ArticleMixin, ListView):
    "归档视图, 按年份对文章进行归档, 返回某年的所有文章"
    context_object_name = 'articles'
    template_name = 'archive.html'

    def get_queryset(self):
        self.year = self.kwargs.get('year')
        current_year = timezone.datetime.today().year

        if int(self.year) not in range(2017, current_year + 1):
            raise Http404

        articles = self.articles.filter(created_time__year=self.year)
        self.count = len(articles)
        return articles

    def get_context_data(self, **kwargs):
        kwargs['year'] = self.year
        kwargs['count'] = self.count
        return super(ArchiveView, self).get_context_data(**kwargs)

blog/templates/widgets/archives-card.html
<div class="articles-right-card">
    <table class="table table-striped table-hover">
        <thead>
            <h5>
                <i class="fa fa-folder-o fa-lg"></i>&nbsp;
                <strong>文章归档</strong>
            </h5>
        </thead>
        <tbody>
            {% for year, num in archives.items %}
            <tr>
                <td class="text-center"><a href="{% url 'blog:archive' year %}">{{ year }}年</a></td>
                <td><span class="badge">{{ num }}</span></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

blog/templates/widgets/article-list.html
{% if articles %}
    {% for article in articles %}
    <article>
        <header>
            <h4>
                <a href="{% url 'blog:article' article.slug %}">
                    {{ article.title }}
                </a>
            </h4>
            <h4>
                <small>
                    <span>Posted:&nbsp;{{ article.created_time|date:"Y-m-d" }}</span>&nbsp;&nbsp;
                    <span class="h6">Tag:&nbsp;{{ article.tag }}</span>&nbsp;&nbsp;
                    <span>Visits:&nbsp;{{ article.visited_times }}</span>&nbsp;&nbsp;
                    <span>Comments:&nbsp;{{ article.comment_set.count }}</span>
                </small>
            </h4>
        </header>
        <div>
        <p>{{ article.summary }}......</p>
        <p>
            <a href="{% url 'blog:article' article.slug %}">
                <button class="btn btn-primary btn-sm pull-right">阅读全文</button>
            </a>
        </p>
        </div>
    </article>
    {% endfor %}

    <!-- 翻页 -->
    {% include 'widgets/paginator.html' %}

{% else %}
    <article>
        <h5>此处暂无文章。</h5>
    </article>
{% endif %}

blog/templates/widgets/search-card.html
<div class="articles-right-card">
        <h5><strong><i class="fa fa-search fa-lg"></i>&nbsp;搜索文章</strong></h5>
        <div class="col-md-11">
            <form class="form-horizontal" role="form" method="get" action="{% url 'blog:search' %}">
                <div class="form-group">
                    <div class="col-md-10" id="search-box">
                        <input type="search" class="form-control" id="search"
                            name="key" placeholder="请输入中文或英文关键词">
                    </div>
                    <div class="col-md-2">
                        <button class="btn btn-info" id="search-btn">go</button>
                    </div>
                </div>
                <span class="text-danger" id="search-err"></span>
            </form>
        </div>
    </div>

blog/templates/widgets/tags-card.html
<div class="articles-right-card">
    <h5><strong><i class="fa fa-tags fa-lg"></i>&nbsp;标签</strong></h5>
    <div id="tags-box" class="tag">
        <h5>
            {% if tags %}
                {% for tag in tags %}
                &nbsp;
                <a href="{% url 'blog:tag' tag.id %}">
                    <span class="label label-danger">{{ tag.name }}</span>
                </a>
                &nbsp;
                {% endfor %}
            {% else %}
                <p>暂无分类</p>
            {% endif %}
       </h5>
   </div>
</div>