blog/urls.py
from django.conf.urls import url

from .views import (BlogView, TagView, ArchiveView, SearchView,
                    ArticleView)


urlpatterns = [
    # Examples:
    # url(r'^$', 'jonah.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', BlogView.as_view(), name='index'),
    url(r'^search$', SearchView.as_view(), name='search'),
    url(r'^tag/(?P<tag_id>[0-9]{1,2})/$', TagView.as_view(), name='tag'),
    url(r'^archive/(?P<year>20[0-9]{2})/$', ArchiveView.as_view(),
        name='archive'),
    url(r'^article/(?P<slug>[0-9a-zA-Z_-]+)$', ArticleView.as_view(),
        name='article'),
]

comment/urls.py
from django.conf.urls import url

from .views import CommentCreateView, comment_upvote, SubCommentCreateView


urlpatterns = [
    # Examples:
    # url(r'^$', 'jonah.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^(?P<slug>[0-9a-zA-Z_-]+)/comment-create$',
        CommentCreateView.as_view(), name='comment-create'),
    url(r'^comment/(?P<comment_id>[0-9]+)/upvote/$',
        comment_upvote, name='comment-upvote'),
    url(r'^comment/(?P<comment_id>[0-9]+)/subcomment-create$',
        SubCommentCreateView.as_view(), name='subcomment-create'),
]

project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.views.generic import TemplateView

from blog import views as blog_views, urls as blog_urls
from comment import urls as comment_urls
from message import urls as message_urls

urlpatterns = [
    # Examples:
    # url(r'^$', 'project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', blog_views.HomeView.as_view(), name='home'),
    url(r'^blog/', include(blog_urls, namespace='blog', app_name='blog')),
    url(r'^comment/', include(comment_urls, namespace='comment',
                              app_name='comment')),
    url(r'^message/', include(message_urls, namespace='message',
                              app_name='message')),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'),
        name='about')
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),
    ]

comment/models.py
from django.db import models

from blog.models import Article

# Create your models here.


class Comment(models.Model):
    "评论模型"
    nickname = models.CharField(max_length=32, verbose_name='昵称')
    email = models.EmailField(verbose_name='邮箱')
    content = models.TextField(max_length=1000, verbose_name='内容')
    up_times = models.IntegerField(default=0, verbose_name='赞同')
    related_article = models.ForeignKey(Article, verbose_name='文章')
    created_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = verbose_name = "评论"
        ordering = ['created_time']

    def __str__(self):
        return self.nickname + '的评论'


class SubComment(models.Model):
    "评论回复模型"
    nickname = models.CharField(max_length=32, verbose_name='昵称')
    email = models.EmailField(verbose_name='邮箱')
    content = models.TextField(max_length=1000, verbose_name='内容')
    related_comment = models.ForeignKey(Comment, verbose_name='评论')
    created_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = verbose_name = "评论回复"
        ordering = ['created_time']

    def __str__(self):
        return self.nickname + '的评论回复'

comment/forms.py
import re
from django import forms
from django.core.exceptions import ValidationError
from .models import Comment, SubComment


class CommentForm(forms.ModelForm):
    "评论表单"
    class Meta:
        model = Comment
        fields = ['nickname', 'email', 'content']

    def clean_nickname(self):
        nickname = self.cleaned_data['nickname'].strip()
        if nickname:
            if not re.fullmatch(r'[\w.@_-]+', nickname):
                raise ValidationError('昵称包含不可识别字符', code='invalid')
        return nickname

    def clean_content(self):
        return self.cleaned_data['content'].strip()


class SubCommentForm(CommentForm):
    "评论回复表单"
    class Meta:
        model = SubComment
        fields = ['nickname', 'email', 'content']

comment/views.py
from django.shortcuts import (HttpResponse, HttpResponseRedirect,
                              get_object_or_404, render_to_response)
from django.http import HttpResponseBadRequest
from django.views.generic.edit import CreateView
from django.views.decorators.http import require_http_methods

from blog.models import Article
from .models import Comment, SubComment
from .forms import CommentForm, SubCommentForm

# Create your views here.


class CommentCreateView(CreateView):
    "创建评论"
    form_class = CommentForm
    template_name = 'article-detail.html'

    def get_success_url(self):
        return '/article/' + self.slug  # 跳转到文章页

    def form_valid(self, form):
        self.slug = self.kwargs.get('slug')
        com = Comment()
        com.nickname = form.cleaned_data['nickname']
        com.email = form.cleaned_data['email']
        com.content = form.cleaned_data['content']
        com.related_article = get_object_or_404(Article, slug=self.slug)
        com.save()
        if self.request.is_ajax():
            return render_to_response('widgets/comment-new.html',
                                      {'comment': com})
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        self.slug = self.kwargs.get('slug')
        if self.request.is_ajax():
            return render_to_response('widgets/form-ajax-invalid.html',
                                      self.get_context_data(form=form))
        return self.render_to_response(self.get_context_data(form=form,
                                                             slug=self.slug))


@require_http_methods(['POST'])
def comment_upvote(request, comment_id):
    "点赞及取消点赞"
    comment = get_object_or_404(Comment, id=comment_id)
    num = request.POST.get('addNum', '')

    try:
        num = int(num)
    except ValueError:
        raise HttpResponseBadRequest()

    # 点赞为 1, 取消点赞为 -1
    if num not in (-1, 1):
        return HttpResponseBadRequest()
    comment.up_times += int(num)
    comment.save()
    return HttpResponse('%s' % comment.up_times)


class SubCommentCreateView(CreateView):
    "对评论创建回复"
    form_class = SubCommentForm
    template_name = 'subcomment-new.html'
    success_url = ''

    def form_valid(self, form):
        comment_id = self.kwargs.get('comment_id')
        sub = SubComment()
        sub.nickname = form.cleaned_data['nickname']
        sub.email = form.cleaned_data['email']
        sub.content = form.cleaned_data['content']
        sub.related_comment = get_object_or_404(Comment, id=comment_id)
        sub.save()
        if self.request.is_ajax():
            return render_to_response('widgets/comment-new.html',
                                      {'subcomment': sub})
        return HttpResponse('<h4>&nbsp;回复成功！</h4>')

    def form_invalid(self, form):
        if self.request.is_ajax():
            return render_to_response('widgets/form-ajax-invalid.html',
                                      self.get_context_data(form=form))
        return HttpResponse('<h4>回复失败。原因：</h4><p>%s</p>' % form.errors)

comment/templates/widgets/comment-form.html
<form class="form-horizontal" method="post" role="form"
    action="{% spaceless %}{%if article %}
                                {% url 'comment:comment-create' article.slug %}
                            {% else %}
                                {% url 'comment:comment-create' slug %}
                            {% endif %}{% endspaceless %}">
    {% csrf_token %}
    <div class="form-group">
        <label class="col-sm-1 control-label" for="comment-nickname">昵称</label>
        <div class="col-sm-4">
            {{ form.errors.nickname }}
            <input type="text" class="form-control" id="comment-nickname"
                name="nickname" value="{{form.data.nickname}}"
                placeholder="仅限中文，数字，字母和@_-"/>
        </div>
        <h5></h5>
    </div>
    <div class="form-group">
        <label class="col-sm-1 control-label" for="comment-email">邮箱</label>
        <div class="col-sm-4">
            {{ form.email.errors }}
            <input type="email" class="form-control" id="comment-email"
                name="email" value="{{form.data.email}}"
                placeholder="不会公开，请放心填写～"/>
        </div>
        <h5></h5>
    </div>
    <div class="form-group">
        <label class="col-sm-1 control-label" for="comment-content">内容</label>
        <div class="col-sm-8">
            {{ form.errors.content }}
            <textarea rows="6" class="form-control" id="comment-content"
                name="content" placeholder="你的评论(1000字以内)..."
                >{{form.data.content}}</textarea>
        </div>
        <h5></h5>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-1 col-sm-11">
            <button type="submit" class="btn btn-primary"
                data-loading-text="正在上传...">
                 提交
             </button>&nbsp;&nbsp;&nbsp;&nbsp;
        </div>
    </div>
</form>

comment/templates/widgets/comment-list.html
{% for comment in comments %}
<div class="comment-box">
    <h5 class="text-muted">
        <label class="label label-info">{{ forloop.counter|add:prev_num }}楼</label>&nbsp;
        <strong>{{ comment.nickname }}</strong>
        <span class="h6">
            发表于&nbsp;{{ comment.created_time|date:"Y-m-d H:i" }}
        </span>
    </h5>
    <div class="comment">
        <p>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            {{comment.content}}
            <span class="h6 pull-right text-primary">
                <span class="comment-up"
                    data-target="{% url 'comment:comment-upvote' comment.id %}">
                    <i class="fa fa-thumbs-o-up" >&nbsp;({{ comment.up_times }})</i>
                </span>&nbsp;&nbsp;
                <span class="subcomment-add" id="add-to-comment-{{comment.id}}"
                    data-target="{% url 'comment:subcomment-create' comment.id %}">
                    回复</span>&nbsp;&nbsp;
            </span>
        </p>
    </div>
    {% for subcomment in comment.subcomment_set.all %}
    <div class="subcomment">
        <p class="h5 text-muted">
            <strong>{{ subcomment.nickname }}</strong>
            <span class="h6">回复</span>
        </p>
        <p>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ subcomment.content }}
            <span class="h6 text-muted">
                &nbsp;&nbsp;{{ subcomment.created_time|date:"Y-m-d H:i" }}
            </span>
        </p>
    </div>
    {% endfor %}
</div>
{% endfor %}

{% if page_obj.has_next %}
<div id="comment-more" class="text-center">
    <a href="?page={{ page_obj.next_page_number }}">
        加载第&nbsp;{{ page_obj.next_page_number }}&nbsp;页
        &nbsp;(共{{ page_obj.paginator.num_pages }}页)
    </a>
</div>
{% else %}
    <div class="text-center">- 已无更多 -<div>
{% endif %}

comment/templates/widgets/comment-new.html
{% if comment %}
<div class="comment-box bg-success">
    <h5 class="text-muted">
        <label class="label label-danger">我的评论</label>&nbsp;
        <strong>{{ comment.nickname }}</strong>
        <span class="h6">
            发表于&nbsp;{{ comment.created_time|date:"Y-m-d H:i" }}
        </span>
    </h5>
    <div class="comment">
        <p>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{comment.content}}
            <span class="h6 pull-right text-primary">
                <span class="comment-up"
                    data-target="{% url 'comment:comment-upvote' comment.id %}">
                    <i class="fa fa-thumbs-o-up" >&nbsp;({{ comment.up_times }})</i>
                </span>&nbsp;&nbsp;
                <span class="subcomment-add" id="add-to-comment-{{comment.id}}"
                    data-target="{% url 'comment:subcomment-create' comment.id %}">
                    回复
                </span>&nbsp;&nbsp;
            </span>
        </p>
    </div>
</div>
{% elif subcomment %}
<div class="subcomment bg-success">
    <h5 class="text-muted">
        <label class="label label-danger">我的回复</label>&nbsp;
        <strong>{{ subcomment.nickname }}</strong>
        <span class="h6">回复</span>
    </h5>
    <p>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ subcomment.content }}
        <span class="h6 text-muted">
            &nbsp;&nbsp;{{ subcomment.created_time|date:"Y-m-d H:i" }}
        </span>
    </p>
</div>
{% endif %}