blog/urls.py
from django.conf.urls import url

from .views import (BlogView, TagView, ArchiveView, SearchView,
                    ArticleView)


urlpatterns = [
    # Examples:
    # url(r'^$', 'jonah.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', BlogView.as_view(), name='index'),
    url(r'^search$', SearchView.as_view(), name='search'),
    url(r'^tag/(?P<tag_id>[0-9]{1,2})/$', TagView.as_view(), name='tag'),
    url(r'^archive/(?P<year>20[0-9]{2})/$', ArchiveView.as_view(),
        name='archive'),
    url(r'^article/(?P<slug>[0-9a-zA-Z_-]+)$', ArticleView.as_view(),
        name='article'),
]

project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.views.generic import TemplateView

from blog import views as blog_views, urls as blog_urls
from comment import urls as comment_urls
from message import urls as message_urls

urlpatterns = [
    # Examples:
    # url(r'^$', 'project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', blog_views.HomeView.as_view(), name='home'),
    url(r'^blog/', include(blog_urls, namespace='blog', app_name='blog')),
    url(r'^comment/', include(comment_urls, namespace='comment',
                              app_name='comment')),
    url(r'^message/', include(message_urls, namespace='message',
                              app_name='message')),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'),
        name='about')
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),
    ]

templates/about.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}关于{% endblock %}

{% block content %}
<div class="col-md-10 col-md-offset-1" id="about-content">
    <h4><i class="fa fa-address-card-o fa-lg"></i>&nbsp;关于博主</h4>
    <div>
        <label class="label label-primary">理想主义</label>
        <label class="label label-danger">有好奇心</label>
        <label class="label label-warning">坚持不懈</label>
        <label class="label label-info">Python</label>
        <label class="label label-success">JavaScript</label>
    </div>
    <div class="about-box row">
        <div class="col-md-10 col-md-offset-1">
            <h4>&lt;<span class="text-info">profile</span>&gt;</h4>
            <h4 class="layer2">&lt;<span class="text-info">basic-info</span>&gt;</h4>
            <h4 class="layer3">&lt;<span class="text-info">name</span>&gt;名字&lt;/<span class="text-info">name</span>&gt;</h4>
            <h4 class="layer3">&lt;<span class="text-info">birthday</span>&gt;生日&lt;/<span class="text-info">birthday</span>&gt;</h4>
            <h4 class="layer3">&lt;<span class="text-info">hometown</span>&gt;籍贯&lt;<span class="text-info">hometown</span>&gt;</h4>
            <h4 class="layer3">&lt;<span class="text-info">personality</span>&gt;理想主义、有好奇心、敢于尝试、坚持不懈&lt;/<span class="text-info">personality</span>&gt;</h4>
            <h4 class="layer2">&lt;/<span class="text-info">basic-info</span>&gt;</h4>
            <h4 class="layer2">&lt;<span class="text-info">education</span>&gt;</h4>
            <h4 class="layer3">&lt;<span class="text-info">graduate</span>&gt;毕业院校&lt;/<span class="text-info">graduate</span>&gt;</h4>
            <h4 class="layer3">&lt;<span class="text-info">major</span>&gt;专业&lt;/<span class="text-info">major</span>&gt;</h4>
            <h4 class="layer3">&lt;<span class="text-info">degree</span>&gt;学位&lt;/<span class="text-info">degree</span>&gt;</h4>
            <h4 class="layer3">&lt;<span class="text-info">language-skill</span>&gt;CET-6&lt;/<span class="text-info">language-skill</span>&gt;</h4>
            <h4 class="layer2">&lt;/<span class="text-info">education</span>&gt;</h4>
            <h4 class="layer2">&lt;<span class="text-info">contact</span>&gt;</h4>
            <h4 class="layer3">&lt;<span class="text-info">qq</span>&gt;123456789&lt;/<span class="text-info">qq</span>&gt;</h4>
            <h4 class="layer3">&lt;<span class="text-info">email</span>&gt;example@gmail.com&lt;/<span class="text-info">email</span>&gt;</h4>
            <h4 class="layer3">&lt;<span class="text-info">github</span>&gt;<a href="https://github.com/liaozhaonan">https://github.com/liaozhaonan</a>&lt;/<span class="text-info">github</span>&gt;</h4>
            <h4 class="layer2">&lt;/<span class="text-info">contact</span>&gt;</h4>
            <h4>&lt;/<span class="text-info">profile</span>&gt;</h4>
            <br/>
            <h4>"<span class="text-danger">Programming_skills</span>": {</h4>
            <h4 class="layer2">"<span class="text-danger">Languages</span>" :  ["Python", "JavaScript"],</h4>
            <h4 class="layer2">"<span class="text-danger">Frameworks</span>": ["Django", "Bootstrap"],</h4>
            <h4 class="layer2">"<span class="text-danger">Library</span>": "JQuery",</h4>
            <h4 class="layer2">"<span class="text-danger">Database</span>": "MySQL",</h4>
            <h4 class="layer2">"<span class="text-danger">Web</span>": "HTTP"</h4>
            <h4>}</h4>
        </div>
    </div>
    <h4><i class="fa fa-gear fa-lg"></i>关于博客</h4>
    <div>
        <label class="label label-success">个人成长</label>
        <label class="label label-primary">编程技术</label>
        <label class="label label-danger">交流经验</label>
        <label class="label label-info">生活感悟</label>
    </div>
    <div class="about-box">
        <h4 class="text-info">简介</h4>
        <p class="layer2">本博客建于2017年12月20日。</p>
        <p class="layer2">本博客用于记录个人工作中的用到的技术知识、反思，以及生活中的感悟。</p>
        <br/>
        <h4 class="text-info">更新</h4>
        <p class="layer2">尚无更新</p>
    </div>
</div>
{%endblock%}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}首页{% endblock%} - zhaonan的网络日志</title>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="author" content="liaozhaonan"/>
    <meta name="robots" content="index,follow"/>
    <meta name="keywords" content="技术博客,JavaScript,Python,Web"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0,
        maximum-scale=1, user-scalable=no"/>
    <meta name="description" content="个人博客用于记录JavaScript, Python,
        Web等技术的学习和使用心得,以及读书体会和生活感想等"/>
    <link rel="stylesheet" type="text/css"
        href="{% static 'bootstrap/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css"
        href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}"/>
    <link rel="stylesheet"
        href="{% static 'font-awesome/css/font-awesome.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"/>
    {% block css %}{% endblock %}
    <!--[if lt IE 9]>
    <script src="https:// oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js">
    </script>
    <script src="https:// oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js">
    </script>
    <![endif]-->
</head>
<body>
    <header>
        {% include 'widgets/nav.html' %}
    </header>
    {% block cover %}
    <img src="{% static 'images/cover.png' %}" alt="" id="img-cover">
    {% endblock %}
    <!-- 主内容区 begin -->
    <div id="main-content">
        {% block content %}{% endblock %}
    </div>
    <!-- 主内容区 end -->
    <a id="back-to-top" href="#">
        <img  src="{% static 'images/top.png' %}">
        <p>返回顶部</p>
    </a>
    <div class="footer">
        <div class="hidden-xs text-center">
            <hr/>
            <ul class="list-inline">
                <li>zhaonan'blog</li>
                <li>基于:
                    <a href="http://www.djangoproject.com/" target="_blank">
                        Django
                    </a>
                </li>
                <li>
                    <a href="http://getbootstrap.com/" target="_blank">
                        Bootstrap
                    </a>
                </li>
                <li>
                    <a href="http://www.fontawesome.com" target="_blank">
                        Font Awesome
                    </a>
                </li>
            </ul>
            <br/>
        </div>
    </div>
    <script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/base.js' %}"></script>
    {% block js %}{% endblock %}
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
<!-- 公告&&提示 -->
<div class="alert alert-info">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        x
    </button>
    <p><li class="fa fa-volume-up"></li>&nbsp;{{ notice }}</p>
</div>
<!-- #home-panels begin -->
<div id="home-panels" class="row">
    <!-- 左边面板 begin -->
    <div id="home-left-panel" class="col-md-4">
        <!-- 最新文章 begin -->
        <div class="well card">
            <table class="table table-striped table-hover">
                <thead>
                    <h5>
                        <i class="fa fa-clock-o fa-lg"></i>
                        <strong>最新文章</strong>
                    </h5>
                </thead>
                <tbody>
                    {% for recent in recents %}
                    <tr>
                        <td class="col-xs-2">{{ forloop.counter }}</td>
                        <td>
                            <a href="{% url 'blog:article' recent.slug %}">
                            {{ recent.title }}
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- 最新文章 end -->
        <!-- 热门文章 begin -->
        <div class="well card">
            <table class="table table-striped table-hover">
                <thead>
                    <h5>
                        <i class="fa fa-star fa-lg"></i>
                        <strong>热门文章</strong>
                    </h5>
                </thead>
                <tbody>
                    {% for hot in hots %}
                    <tr>
                        <td class="col-xs-2">{{ forloop.counter }}</td>
                        <td>
                            <a href="{% url 'blog:article' hot.slug %}">
                            {{ hot.title }}
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- 热门文章 end -->
    </div>
    <!-- 左边面板 end -->
    <!-- 右边面板 begin -->
    <div class="col-md-8">
        <!-- 推荐阅读 begin -->
        <div id="recommend-box" class="card">
            <h5>
                <i class="fa fa-bolt fa-lg"></i>
                <strong>推荐阅读</strong>
            </h5>
            <div data-ride="carousel" id="recommend-body"
                class="carousel slide">
                <!-- 图片容器 -->
                <div class="carousel-inner">
                    {% if recommends %}
                        {% for recommend in recommends %}
                        <div class="item {% if forloop.counter == 1 %}
                                            active
                                        {% endif %}">
                            <img src="{{ recommend.recommend_pic.url }}"
                                alt="{{ recommend.title }}"/>
                            <div class="carousel-caption">
                                <a href="{% url 'blog:article' recommend.slug %}">
                                    <h3>{{ recommend.title }}</h3>
                                    <p>{{ recommend.summary }}</p>
                                </a>
                            </div>
                        </div>
                        {% endfor %}
                    {% else %}
                        <div class="item active">
                            <img src="{% static 'images/recommend/default.jpg' %}" alt="尚无推荐"/>
                            <div class="carousel-caption">
                                <h3>尚无推荐</h3>
                            </div>
                        </div>
                    {% endif %}
                </div>
                <!-- 圆圈指示符 -->
                <ol class="carousel-indicators">
                    {% if recommends %}
                        {% for recommend in recommends %}
                        <li data-slide-to="{{ forloop.counter0 }}"
                            data-target="#recommend-body">
                        </li>
                        {% endfor %}
                    {% else %}
                        <li data-slide-to="0" data-target="#recommend-body">
                        </li>
                    {% endif %}
                </ol>
                <!-- 左右按钮 -->
                <a data-slide="prev" class="left carousel-control"
                    href="#recommend-body">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a data-slide="next" class="right carousel-control"
                     href="#recommend-body">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
            </div>
        </div>
        <!-- 推荐阅读 end -->
        <!-- 文章专栏介绍 begin -->
        <div class="intro-group">
            <div class="col-md-3 intro text-center text-muted">
                <a href="{% url 'blog:index' %}?column=1">
                    <span class="fa-stack fa-3x text-danger">
                        <i class="fa fa-circle-thin fa-stack-2x"></i>
                        <i class="fa fa-keyboard-o fa-stack-1x"></i>
                    </span>
                </a>
                <div>
                    <h4>编程</h4>
                    <p>探讨技术，交流经验</p>
                </div>
            </div>
            <div class="col-md-3 intro text-center text-muted">
                <a href="{% url 'blog:index' %}?column=2">
                    <span class="fa-stack fa-3x text-primary">
                        <i class="fa fa-circle-thin fa-stack-2x"></i>
                        <i class="fa fa-book fa-stack-1x"></i>
                    </span>
                </a>
                <div>
                    <h4>读书</h4>
                    <p>分享知识，表达观点</p>
                </div>
            </div>
            <div class="col-md-3 intro text-center text-muted">
                <a href="{% url 'blog:index' %}?column=3">
                    <span class="fa-stack fa-3x text-success">
                        <i class="fa fa-circle-thin fa-stack-2x"></i>
                        <i class="fa fa-pencil fa-stack-1x"></i>
                    </span>
                </a>
                <div>
                    <h4>随笔</h4>
                    <p>生活有感，碎碎念之</p>
                </div>
            </div>
            <div class="col-md-3 intro text-center text-muted">
                <span class="fa-stack fa-3x text-info">
                    <i class="fa fa-circle-thin fa-stack-2x"></i>
                    <i class="fa fa-plus fa-stack-1x"></i>
                </span>
            <div>
                <h4>其他</h4>
                <p>更多栏目，敬请期待</p>
            </div>
        </div>
        <!-- 专栏介绍 end -->
    </div>
    <!-- 右边面板 end -->
</div>
<!-- #home-panels end -->
{% endblock %}